services:
  _defaults:
    autowire: true
    autoconfigure: true
  hierarchical_routes_param_converter:
    class: TwoKings\Hierarchy\ParamConverter
    tags:
      - { name: request.param_converter, converter: hierarchical_routes_param_converter }
  TwoKings\Hierarchy\HierarchicalCanonical:
    decoration_priority: 1
    decorates: Bolt\Canonical
    # decorates: Bolt\Cache\CanonicalCacher
